### ISSUE TITLE
Some (Maybe most) code examples should not show to the right of everything

### ISSUE THREAD

**Issue by Fnige** [applejuiceyy/figs#5]
![image](https://user-images.githubusercontent.com/35159947/193281749-9ba6c5fe-344b-488e-976f-18d5a846af2a.png)
Here is an example

I dont know if this is actually intentional but it looks shit so its an issue

**Comment by applejuiceyy** [comment]
would it be better to put these example codeblocks top-aligned with the method block?

**Comment by Fnige** [comment]
Honestly nearly anywhere within the box (or whatever the light grey area is called) would work
